name: Deploy to Dev
"on":
  push:
    branches:
      - dev

env:
  REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
  REACT_APP_DISCORD_ID: ${{ secrets.REACT_APP_DISCORD_ID }}
  REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
  REACT_APP_FIREBASE_DATABASE_URL: ${{ secrets.REACT_APP_FIREBASE_DATABASE_URL }}
  REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
  REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
  REACT_APP_GAME_ID: ${{secrets.REACT_APP_GAME_ID}}
  REACT_APP_COOKBOOK_ID: ${{secrets.REACT_APP_COOKBOOK_ID}}
  REACT_APP_CLIENT_ID: ${{secrets.REACT_APP_CLIENT_ID}}
  REACT_APP_ACCESS_TOKEN: ${{secrets.REACT_APP_ACCESS_TOKEN}}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v2
      - run: yarn && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_COOKBOOK_1D93F }}"
          channelId: live
          projectId: cookbook-1d93f
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
